import Head from "next/head";
import CoinList from "../components/CoinList";
import Navbar from "../components/Navbar";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Crypto Rankings</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <main>
        <CoinList />
      </main>
    </div>
  );
}
